TesteUsuario/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import conetar, disconetar,  carregarFoto, confirmacao, editar, apagar, carregarFoto, registar, principal, index, visualFoto

app_name ="TesteUsuario"

urlpatterns = [

    path("", registar, name="registar"),
    path("carregar?fotos!", carregarFoto, name="carregarFoto"),
    path("principal", principal, name="principal"),
    path("index", index, name = "index"),
    path("visual<int:id>", visualFoto, name="visualFoto"),
    path("editar<int:id>", editar, name="editar"),
    path("apagar<int:id>", apagar, name="apagar"),
    path("confirma<int:id>", confirmacao, name="confirmacao"),
    path("conectar", conetar, name="conetar"),
    path("disconetar", disconetar, name="disconetar")

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("TesteUsuario.urls"))
]

TesteUsuario/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.

class User(AbstractUser):
    nome = models.CharField(max_length=40)
    apelido = models.CharField(max_length=40)
    username = models.EmailField("E-mail", max_length=40, unique=True)
    dataNascimento = models.DateField(null=True)


class Foto(models.Model):
    foto = models.ImageField(blank=True)
    titulo = models.CharField(max_length= 50)
    descricao = models.CharField(max_length=500)
    data = models.DateTimeField(auto_now=True)
    usuario = models.ForeignKey(User, models.CASCADE)

TesteUsuario/forms.py
from django.contrib.auth import forms
from django.forms import ModelForm, widgets
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .models import User, Foto


class CriaUsuario(forms.UserCreationForm):
    class Meta(forms.UserCreationForm.Meta):
        model = User
        fields = ["nome", "apelido", "username",  "dataNascimento"]
        

class CriarComentario(ModelForm):
    class Meta:
        model = Foto
        fields = ["foto", "titulo",  "descricao"]

TesteUsuario/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render

# Create your views here.
from TesteUsuario.forms import CriaUsuario, CriarComentario
from TesteUsuario.models import Foto, User


def registar (request):
    usuario = CriaUsuario(request.POST or None)
    
    if request.POST:
        dataNascimento = request.POST["dataNascimento"]
        usuario.instance.dataNascimento = dataNascimento
        if usuario.is_valid():
            usuario.save()
            email = usuario.cleaned_data["username"]
            senha1 = usuario.cleaned_data["password1"]

            usuario = authenticate(username=email, password=senha1)
            login(request, usuario)
            print("OLA")
            return render(request, "principal.html")

    return render(request, "registar.html",  {"form": usuario})



def carregarFoto (request):
    if request.POST:
        post = CriarComentario(request.POST)
        fotos = request.FILES.getlist("imagem")
        descricao = request.POST["descricao"]
        titulo = request.POST["titulo"]
        #Preenche campo de formulario que vem de request e valida
        post.instance.foto = fotos
        post.instance.usuario = request.user
        post.instance.descricao = descricao
        post.instance.titulo = titulo
        if post.is_valid():
            for foto in fotos:
                post = CriarComentario(request.POST)
                post.instance.foto = foto
                post.instance.usuario = request.user
                post.instance.descricao = descricao
                post.instance.titulo = titulo
                post.save()
            fotos = Foto.objects.all()
            context = {"fotos": fotos}
            return render(request, "principal.html", context)
    return render(request, "carregarFoto.html")

def principal (request):
    if request.POST:
        query = request.POST["pesquisa"]
        fotos = Foto.objects.all().filter(titulo=query)
        
        print("ola")
        context = {"fotos": fotos}
        return render(request, "principal.html", context)

    fotos = Foto.objects.all()
    context = {"fotos": fotos}
    return render(request, "principal.html", context)

def index (request):
    if request.POST:
        query = request.POST["pesquisa"]
        fotos = Foto.objects.all().filter(titulo = query)
        context = {"fotos": fotos}
        return render(request, "principal.html", context)
    return render(request, "index.html")


def visualFoto (request, id):
    foto = Foto.objects.all().get(pk=id)
    context = {"fotoVisual": foto}
    return render(request, "visualFoto.html", context)


def editar (request, id):
    intancia = Foto.objects.all().get(pk=id)
    foto = CriarComentario(instance=intancia)
    if request.POST:
        descricao = request.POST["descricao"]
        titulo = request.POST["titulo"]

        fotos = Foto.objects.all()
        foto = CriarComentario(instance=intancia)
        foto.cleaned_data = intancia

        foto.instance.titulo = titulo
        foto.instance.descricao = descricao
        foto.save()
        return render(request, "principal.html", {"fotos": fotos})

    return render(request,"editar.html", {"fotoEditar": foto, "foto": intancia})

def confirmacao(request, id):
    foto = Foto.objects.all().get(pk=id)
    if request.POST:
        foto.delete()
    fotos = Foto.objects.all()
    return render(request, "principal.html", {"fotos": fotos, "fotoApaga": foto})

def apagar(request, id):
    foto = Foto.objects.all().get(pk=id)
    return render(request, "apagar.html", {"fotoApagar": foto})

            
def conetar(request):
    if request.POST:
        email = request.POST["email"]
        senha = request.POST["senha"]
        usuario = authenticate(username=email, password=senha)
        fotos = Foto.objects.all()
        login(request, usuario)
        return render(request, "principal.html", {"fotos": fotos})
    return render(request, "conetar.html")

def disconetar(request):
    logout(request)
    return render(request, "menu.html")

TesteUsuario/templates/apagar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}" >
    <link rel="stylesheet" href="{% static 'css/css/bootstrap.min.css'%}" >
    <script src="{% static 'css/js/bootstrap.bundle.min.js' %}"></script>

</head>



<body>
    

    
    <main>
        <section >
            <img class="vf-img" src="static/{{fotoApagar.foto}}" alt="">
            <div class="d-grid gap-2 col-6 mx-auto">
                <div class="d-grid gap-2 col-6 mx-auto">
                    
                    <a href="{% url 'TesteUsuario:confirmacao' fotoApagar.pk %}" class="btn btn-outline-secondary">
                        <button class="btn btn-outline-danger">Confirmar</button>
                    </a>
                    <a href=" {% url 'TesteUsuario:principal'  %} " class="btn btn-outline-secondary">
                        <button class="btn btn-outline-success" >Cancelar</button>
                    </a>
                </div>
            </div>
        </section>
        
    </main>
            
           

    </main>


</body>
</html>
    


  

TesteUsuario/templates/carregarFoto.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}" >
    <link rel="stylesheet" href="{% static 'css/css/bootstrap.min.css'%}" >
    <script src="{% static 'css/js/bootstrap.bundle.min.js' %}"></script>

</head>



<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-success">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Perfil</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Principal</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Registar</a>
                  </li>

                  <li>
                    <a class="nav-link" href="#">Iniciar Sessão</a>
                  </li>

                </ul>

                <form class="d-flex">
                  <input class="form-control me-2" type="search" placeholder="Buscar..." aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">OK</button>
                </form>

              </div>
            </div>
          </nav>
    </header>


    
    <main>
        <section >
            <h1>Conseguiu chegar aqui {{user.username}}</h1>
    
            <form class="row g-3" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="col-md-12">
                    <label for="imagem" class="form-label">Seleciona Seus ficheiros para guardar</label>
                    <input class="form-control" type="file" multiple name="imagem" id="imagem">
                </div>

                <div class="col-md-12">
                    <label for="titulo" class="form-label">Titulo da foto</label>
                    <input type="text" class="form-control" name="titulo" id="titulo" rows="3"></textarea>         
                </div>

                <div class="col-md-12">
                    <label for="descricao" class="form-label">Descrição de foto</label>
                    <textarea class="form-control" name="descricao" id="descricao" rows="3"></textarea>         
                </div>

                <div class="col-md-12">
                    <input type="submit" class="form-control" id="submit" name="submit">
                </div>
            </form>
        </section>
    </main>
            
      
</body>
</html>
    


  

TesteUsuario/templates/conetar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}" >
    <link rel="stylesheet" href="{% static 'css/css/bootstrap.min.css'%}" >
    <script src="{% static 'css/js/bootstrap.bundle.min.js' %}"></script>

</head>



<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-success">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Perfil</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'TesteUsuario:registar' %}">Registar</a>
                  </li>

                  <li>
                    <div class="formulario">
                      <a href="#" class="dropdown-toggle nav-link" data-bs-toggle="dropdown">Iniciar Sessão</a>
                      <ul class="dropdown-menu">
                        
                        <li class="fomulario-login">
                            
                            <form class="conectar" method="POST">
                              {% csrf_token %}
                              <div class="conectar-email">
                                  <input type="email" class="form-control" id="inputEmail4" name = "email" placeholder="E-mail">
                              </div>
                              <div class="conectar-senha">
                                  <input type="password" class="form-control" id="inputPassword4" name="senha" placeholder="Senha">
                              </div>
              
                              <div class="conectar-logar">
                                <input type="submit" name="submit" value="Entrar">
                              </div>
                            </form>
                        </li>

                      </ul>
                    </div>
                  </li>

                </ul>

                <form class="d-flex">
                  <input class="form-control me-2" type="search" placeholder="Buscar..." aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">OK</button>
                </form>

              </div>
            </div>
          </nav>
    </header>


    
    <main>
        
    </main>

    <section>
        <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
          <div class="caro">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="static/8.png" class="d-block w-100" alt="..." style="width: 200px; height: 650px;">
              </div>
              <div class="carousel-item">
                <img src="static/lobo.jpg" class="d-block w-100" alt="..." style="width: 200px; height: 650px;">
              </div>
              <div class="carousel-item">
                <img src="bissIcon.jpg" class="d-block w-100" alt="..." style="width: 200px; height: 650px;">
              </div>
            </div>
          </div>
          
        </div>
      
    </section>
            
           
</body>
</html>
    


  

TesteUsuario/templates/editar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}" >
    <link rel="stylesheet" href="{% static 'css/css/bootstrap.min.css'%}" >
    <script src="{% static 'css/js/bootstrap.bundle.min.js' %}"></script>

</head>



<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-success">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Perfil</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Principal</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Registar</a>
                  </li>

                  <li>
                    <a class="nav-link" href="#">Iniciar Sessão</a>
                  </li>

                </ul>

                <form class="d-flex">
                  <input class="form-control me-2" type="search" placeholder="Buscar..." aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">OK</button>
                </form>

              </div>
            </div>
          </nav>
    </header>


    
    <main>
        <section>
            <img class="vf-img" src="static/{{foto.foto}}" alt="">
            <form method="post" class="row g-3">
                {% csrf_token %}
                
                <div class="col-md-12">
                    <label for="titulo" class="form-label">titulo</label>
                    <input type="text" value="{{fotoEditar.titulo.value}}" id="titulo" class="form-control" placeholder="Assimiu" name="titulo"> 
                </div>
        
                <div class="col-md-12">
                    <label for="descricao" class="form-label">descricao</label>
                    <textarea value="xcas" id="descricao" class="form-control" placeholder="Assimiu" name="descricao">{{fotoEditar.descricao.value}}</textarea>
                </div>
                
                <div class="col-md-12">
                    <input class="form-control" type="submit" value="Guardar">
                </div>
                
            </form>
        </section>
    </main>
            
        


</body>
</html>
    


  

TesteUsuario/templates/menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}" >
    <link rel="stylesheet" href="{% static 'css/css/bootstrap.min.css'%}" >
    <script src="{% static 'css/js/bootstrap.bundle.min.js' %}"></script>

</head>



<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-success">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Perfil</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Principal</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Registar</a>
                  </li>

                  <li>
                    <a class="nav-link" href="#">Iniciar Sessão</a>
                  </li>

                </ul>

                <form class="d-flex">
                  <input class="form-control me-2" type="search" placeholder="Buscar..." aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">OK</button>
                </form>

              </div>
            </div>
          </nav>
    </header>


    
    <main>
        <section >
           
        </section>
    </main>
          

</body>
</html>
    


  

TesteUsuario/templates/principal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}" >
    <link rel="stylesheet" href="{% static 'css/css/bootstrap.min.css'%}" >
    <script src="{% static 'css/js/bootstrap.bundle.min.js' %}"></script>

</head>



<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-success">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Perfil</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Principal</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Registar</a>
                  </li>

                  <li>
                    <a class="nav-link" href="#">Iniciar Sessão</a>
                  </li>

                </ul>

                <form class="d-flex">
                  <input class="form-control me-2" type="search" placeholder="Buscar..." aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">OK</button>
                </form>

              </div>
            </div>
          </nav>
    </header>


    
    <main>
        <section class="fotografias">
            {% for foto in fotos %}
                <div>
                    <img src="static/{{foto.foto}}" width="200px" alt="">
                    olaldadladcaca
                </div>
            {% endfor %}
           
        </section>
    </main>
          

</body>
</html>
    


  

TesteUsuario/templates/registar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}" >
    <link rel="stylesheet" href="{% static 'css/css/bootstrap.min.css'%}" >
    <script src="{% static 'css/js/bootstrap.bundle.min.js' %}"></script>

</head>



<body><header>
    <nav class="navbar navbar-expand-lg navbar-light bg-success">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Perfil</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Principal</a>
              </li>
              <li>
                <a class="nav-link" href="{% url 'TesteUsuario:conetar' %}">Voltar</a>
              </li>

            </ul>

            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Buscar..." aria-label="Search">
              <button class="btn btn-outline-success" type="submit">OK</button>
            </form>

          </div>
        </div>
      </nav>
</header>

    
    <main>
        <section >

            <form method="post" class="registo">
                {% csrf_token %}
                <div>
                    <label for="validationServer01" class="form-label">Nome</label>
                    <div type="text" class="form-control is-valid" id="validationServer01" name="nome" value="Mark" required> 
                        {{form.nome}}
                    </div>
                    <div class="valid-feedback">
                        Campo obrigatório
                    </div>
                </div>
        
                <div>
                    <label for="validationServer01" class="form-label">Apelido</label>
                    <div type="text" class="form-control is-valid" id="validationServer01" name="apelido" value="Mark" required> 
                        {{form.apelido}}
                    </div>
                    <div class="valid-feedback">
                        Campo obrigatório
                    </div>
                </div>
                <div>
                    <label for="validationServer01" class="form-label">Data de Nascimento</label>
                    <div type="text" class="form-control is-valid" id="validationServer01" name="dataNascimento" value="Mark" required> 
                        <input type="date" name="dataNascimento">
                    </div>
                    <div class="valid-feedback">
                        Campo obrigatório
                    </div>
                </div>
        
                <div>
                    <label for="validationServer01" class="form-label">E-mail</label>
                    <div type="text" class="form-control is-valid" id="validationServer01" name="email" value="Mark" required> 
                        {{form.username}}
                    </div>
                    <div class="valid-feedback">
                        Campo obrigatório
                    </div>
                </div>
                <div>
                    <label for="validationServer01" class="form-label">Senha</label>
                    <div type="text" class="form-control is-valid" id="validationServer01" name="senha1" value="Mark" required> 
                        {{form.password1}}
                    </div>
                    <div class="valid-feedback">
                        Campo obrigatório
                    </div>
                </div>
        
                <div>
                    <label for="validationServer01" class="form-label">Confirmação de senha</label>
                    <div type="text" class="form-control is-valid" id="validationServer01" name="senha2" value="Mark" required> 
                        {{form.password2}}
                    </div>
                    <div class="valid-feedback">
                        Campo obrigatório
                    </div>
                </div>
                
        
                <input type="submit" class="form-control" value="Registar">
                
            </form>
            
        </section>
    </main>
          

</body>
</html>
    


  

TesteUsuario/templates/teste.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script>
        document.addEventListener('DOMContentLoaded', function(){
            let carousInner = document.createElement("div");
            carousInner.className = "carousel-inner"
            let novoAtributo = document.createAttribute("data-bus-interval")
            novoAtributo.value = "1000"
            carousInner.setAttributeNode(novoAtributo)

            let imagem = document.createElement("img")
            imagem.className = "d-block w-100"
            let src = document.createAttribute("src")
            src.value = "static/meus/ficheiros/1.png"
            imagem.setAttributeNode(src)
            carousInner.appendChild(imagem)

            document.body.appendChild(carousInner)
        })

        
        
    </script>
</head>
<body>
    <button id ="n">
        clica
    </button>
    
    <img src="static/meus/ficheiros/1.png" alt="">
    
</body>
</html>

TesteUsuario/templates/visualFoto.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}" >
    <link rel="stylesheet" href="{% static 'css/css/bootstrap.min.css'%}" >
    <script src="{% static 'css/js/bootstrap.bundle.min.js' %}"></script>

</head>



<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-success">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Perfil</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Principal</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Registar</a>
                  </li>

                  <li>
                    <a class="nav-link" href="#">Iniciar Sessão</a>
                  </li>

                </ul>

                <form class="d-flex">
                  <input class="form-control me-2" type="search" placeholder="Buscar..." aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">OK</button>
                </form>

              </div>
            </div>
          </nav>
    </header>


    
    <main>
        <section>
            <img class="vf-img" src="static/{{fotoVisual.foto}}" alt="">

            <div class="d-grid gap-2 col-6 mx-auto">
                <div class="d-grid gap-2 col-6 mx-auto">
                    
                    <a href="{% url 'TesteUsuario:editar' fotoVisual.pk %}" class="btn btn-outline-secondary">
                        <button class="btn btn-outline-success">Editar</button>
                    </a>
                    <a href=" {% url 'TesteUsuario:apagar' fotoVisual.pk %} " class="btn btn-outline-secondary">
                        <button class="btn btn-outline-danger" >Apagar</button>
                    </a>
                </div>
            </div>
        </section>
    </main>
          

</body>
</html>
    


  